### ISSUE TITLE
Default z-index is not set the same way as in the browser

### ISSUE THREAD

**Issue by adamgiebl** [divriots/code.to.design#14]
**Describe the bug**
It seems like the implicit z-index is not being consistent with browser behavior. If z-index is set explicitly it works fine.
![image](https://github.com/divriots/code.to.design/assets/31918685/97b0b84b-c641-4f30-81cd-6bb4b0e742a5)

**To Reproduce**

```html
<div class="container">
  <div class="box"></div>
</div>
```

```css
.container {
  position: relative;
  font-family: sans-serif;
}

.container::before,
.container::after {
  content: "";
  background-color: #fab5704c;
  position: absolute;
}

.container::before {
  border-radius: 50%;
  width: 6rem;
  height: 6rem;
  top: 30%;
  right: 7%;
}

.container .box {
  width: 11.875em;
  height: 15.875em;
  padding: 1rem;
  background-color: rgba(255, 255, 255, 0.074);
  border: 1px solid rgba(255, 255, 255, 0.222);
  -webkit-backdrop-filter: blur(20px);
  backdrop-filter: blur(20px);
  border-radius: 0.7rem;
  transition: all ease 0.3s;
}

```
