### ISSUE TITLE
Text orientation + rotation

### ISSUE THREAD

**Issue by adamgiebl** [divriots/code.to.design#16]
**Describe the bug**
![image](https://github.com/divriots/code.to.design/assets/31918685/0b1b72b6-6c67-4fdf-9b7c-80b2228c39f7)

**To Reproduce**

```html
<div class="card">
  <div class="date-time-container">
    <time class="date-time" datetime="2022-10-10">
      <span>2022</span>
      <span class="separator"></span>
      <span>Oct 10</span>
    </time>
  </div>
  <div class="content"></div>
</div>

```

```css
.card {
  box-sizing: border-box;
  display: flex;
  background-color: rgba(255, 255, 255, 1);
}

.date-time-container {
  writing-mode: vertical-lr;
  transform: rotate(180deg);
  padding: 0.5rem;
}

.date-time {
  display: flex;
  align-items: center;
  justify-content: space-between;
  grid-gap: 1rem;
  gap: 1rem;
  font-weight: 700;
  text-transform: uppercase;
  color: rgba(17, 24, 39, 1);
}

```
