### ISSUE TITLE
font-family ignored

### ISSUE THREAD

**Issue by adamgiebl** [divriots/code.to.design#17]
**Describe the bug**
It seems like any font-family setting is ignored when using the API. It always uses Liberation Sans. This issue is not present when using code.to.design playground.
![image](https://github.com/divriots/code.to.design/assets/31918685/efcbefc3-bb44-4122-8e05-aaf756e9a60a)

**To Reproduce**

```html
<button class="button">Github test button</button>
```

```css
.button {
  font-family: Arial, "Trebuchet MS", Verdana, sans-serif !important;
  color: white;
  background: black;
  border: none;
  padding: 1rem 2rem;
}

```
