### ISSUE TITLE
Simple text split into multiple text blocks in Figma

### ISSUE THREAD

**Issue by adamgiebl** [divriots/code.to.design#19]
**Describe the bug**
![image](https://github.com/divriots/code.to.design/assets/31918685/63470fdb-45a7-4a50-b6ea-1764eea40325)

**To Reproduce**

```html
<div class="card">
  <div class="description">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur at
    posuere eros. Interdum et malesuada fames ac ante ipsum primis in faucibus.
  </div>
</div>
```

```css
.card {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-around;
  font-family: Arial, "Trebuchet MS", Verdana, sans-serif !important;
  width: 260px;
  padding: 20px 1px;
  margin: 10px 0;
  text-align: center;
  position: relative;
  cursor: pointer;
  background: black;
}

.description {
  color: white;
}
```
