### ISSUE TITLE
Relative positioning with transform rotate

### ISSUE THREAD

**Issue by adamgiebl** [divriots/code.to.design#7]
**Describe the bug**
![image](https://github.com/divriots/code.to.design/assets/31918685/32b2c6c2-e255-4ae5-8517-542d17e911eb)

**To Reproduce**
```html
<button class="button">
  <div class="plus1">
    <div class="plus2"></div>
  </div>
</button>
```

```css
.button {
  cursor: pointer;
  width: 70px;
  height: 70px;
  position: relative;
}

.button .plus1 {
  background-color: red;
  rotate: 45deg;
}

.button .plus2 {
  height: 10px;
  background-color: red;
  transform: rotate(90deg);
}

```
